"""
Matsuoka 振動子による中枢パターン生成器（CPG）

各関節に独立した 2 ニューロンペア（屈筋 x1 / 伸筋 x2）を持つ。

ODEs:
  τ  * ẋ1 = -x1 - β*v1 - w*max(x2,0) + I(t)
  τ_r* v̇1 = -v1 + max(x1,0)
  (x2, v2 は対称)

出力: y_i = max(x1_i, 0) - max(x2_i, 0)  ← [-amplitude, +amplitude] の周期信号

Reference:
  Matsuoka (1985) Sustained oscillations generated by mutually inhibiting
  neurons with adaptation. Biol. Cybern. 52, 367-376.
"""

from __future__ import annotations

import numpy as np


class MatsuokaOscillator:
    """
    n_joints 個の独立 Matsuoka 振動子。

    Parameters
    ----------
    n_joints   : 振動子の数（= 制御する関節数）
    tau        : 膜時定数 [s]（周波数の主パラメータ）
    tau_r      : 適応時定数 [s]（通常 tau_r > tau）
    beta       : 適応フィードバックゲイン
    w          : 相互抑制重み
    amplitude  : 出力スケーリング [rad]
    dt         : 積分ステップ [s]
    """

    def __init__(
        self,
        n_joints:  int   = 5,
        tau:       float = 0.25,
        tau_r:     float = 0.50,
        beta:      float = 2.5,
        w:         float = 2.0,
        amplitude: float = 0.3,
        dt:        float = 0.002,
        alpha_fb:  float = 0.0,
    ):
        self.n = n_joints
        self.tau = tau
        self.tau_r = tau_r
        self.beta = beta
        self.w = w
        self.amplitude = amplitude
        self.dt = dt
        self.alpha_fb = alpha_fb   # 固有受容器フィードバックゲイン（0.0 でFBなし）

        rng = np.random.default_rng(0)
        self.x1 = rng.uniform(0.0, 0.5, n_joints)
        self.x2 = rng.uniform(0.0, 0.5, n_joints)
        self.v1 = np.zeros(n_joints)
        self.v2 = np.zeros(n_joints)

    def reset(self, seed: int = 0) -> None:
        rng = np.random.default_rng(seed)
        self.x1 = rng.uniform(0.0, 0.5, self.n)
        self.x2 = rng.uniform(0.0, 0.5, self.n)
        self.v1 = np.zeros(self.n)
        self.v2 = np.zeros(self.n)

    def step(
        self,
        I:   np.ndarray | None = None,
        r_q: np.ndarray | None = None,
    ) -> np.ndarray:
        """
        Euler 1 ステップ進め、出力 y (n,) を返す。

        Parameters
        ----------
        I   : 外部入力 (n,)。None なら定常入力 1.0。
        r_q : LIF 固有受容器からの符号付き発火率 (n,) ∈ [-1, 1]。
              None なら固有受容器フィードバックなし（後方互換）。
              位相補正として I に加算: I_eff = I + alpha_fb * r_q
        """
        if I is None:
            I = np.ones(self.n)
        if r_q is not None and self.alpha_fb != 0.0:
            I = I + self.alpha_fb * r_q

        rx1 = np.maximum(self.x1, 0.0)
        rx2 = np.maximum(self.x2, 0.0)

        dx1 = (-self.x1 - self.beta * self.v1 - self.w * rx2 + I) / self.tau
        dx2 = (-self.x2 - self.beta * self.v2 - self.w * rx1 + I) / self.tau
        dv1 = (-self.v1 + rx1) / self.tau_r
        dv2 = (-self.v2 + rx2) / self.tau_r

        self.x1 += dx1 * self.dt
        self.x2 += dx2 * self.dt
        self.v1 += dv1 * self.dt
        self.v2 += dv2 * self.dt

        return self.amplitude * (np.maximum(self.x1, 0.0) - np.maximum(self.x2, 0.0))

    @property
    def state(self) -> np.ndarray:
        """現在の状態 [x1, x2] (2n,) を返す（CfC への入力に使う）。"""
        return np.concatenate([self.x1, self.x2])
